spring:
  application:
    name: MarketplaceClone
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/listings
    username: postgres
    password: '0000'